---
- name: Accept xcodebuild license
  shell: xcodebuild -license accept
  ignore_errors: yes
  become: yes

- name: Install Zsh packages
  shell: brew install zsh zsh-completions zsh-autosuggestions

- name: Tap fonts
  homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: Install fira code
  shell: brew tap homebrew/cask-fonts && brew install --cask font-fira-code

- name: Install casks
  shell: brew install --cask visual-studio-code slack warp

- name: Install pyenv
  shell: brew install pyenv

- name: Install python 3
  command: "pyenv install 3.8.6"

- name: Set python 3
  command: "pyenv global 3.8.6"

- name: Install Pipenv
  shell: pip install pipenv

- name: Install the fuck package
  shell: brew install thefuck
